title:               The First Cry of Atom
tagline:             Today is the first day of the rest of my life.

# Authors documented under _data

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'https-lenpaul-github-io-lagrange'

google-ID: 'UA-44055098-1'

menu:
- {name: 'About', path: 'menu', url: 'about.html'}
- {name: 'Writing', path: 'menu', url: 'writing.html'}
- {name: 'Contact', path: 'menu', url: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github', link: 'https://www.github.com/Lewuathe'}
- {icon: 'twitter', link: 'https://twitter.com/Lewuathe'}
- {icon: 'linkedin', link: 'http://www.linkedin.com/in/kaisasaki/'}
- {icon: 'rss-square', link: 'feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy:'

post_date_prefix: 'Written on'
